"""add_new_fields_to_users_table

Revision ID: 10e67c83c7c6
Revises: f1290be08812
Create Date: 2025-10-08 23:32:02.929202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '10e67c83c7c6'
down_revision: Union[str, None] = 'f1290be08812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpatientcenter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('currentPatients', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outpatientcenter', schema=None) as batch_op:
        batch_op.drop_column('currentPatients')
        batch_op.drop_column('capacity')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
