"""Add TokenBlacklist table

Revision ID: 9f10008eaad2
Revises: 7baa139f2b38
Create Date: 2025-09-27 17:02:43.628426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9f10008eaad2'
down_revision: Union[str, None] = '7baa139f2b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokenblacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokenblacklist_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokenblacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokenblacklist_token'))

    op.drop_table('tokenblacklist')
    # ### end Alembic commands ###
